# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(verbose_name='time of departure')),
                ('departure_mileage', models.IntegerField(default=0)),
                ('departure_location', models.CharField(max_length=64)),
                ('arrival_time', models.DateTimeField(verbose_name='time of departure')),
                ('arrival_mileage', models.IntegerField(default=0)),
                ('arrival_location', models.CharField(max_length=64)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autologbackend.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=8)),
                ('vehicle_make', models.CharField(max_length=32)),
                ('vehicle_model', models.CharField(max_length=32)),
                ('mileage', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autologbackend.Vehicle'),
        ),
    ]
