# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 23:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autologbackend', '0003_auto_20160925_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='mileage',
        ),
    ]
