# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autologbackend', '0004_remove_vehicle_mileage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(default=0.0)),
                ('lon', models.FloatField(default=0.0)),
                ('description', models.CharField(max_length=64)),
            ],
        ),
    ]
