# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autologbackend', '0005_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='arrival_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='autologbackend.Location'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='autologbackend.Location'),
        ),
    ]
